services:
  - type: worker
    name: hr-attendance-automation
    env: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    envVars:
      - key: TZ
        value: Asia/Kolkata
      - key: NODE_ENV
        value: production
      - key: HEADLESS
        value: "true"
      - key: SCREENSHOTS_ENABLED
        value: "true"
      - key: NOTIFICATIONS_ENABLED
        value: "true"
      - key: LOGIN_TIME
        value: "09:30"
      - key: LOGOUT_TIME
        value: "19:30"
      - key: RANDOM_DELAY
        value: "5"
      - key: HR_USERNAME
        sync: false
      - key: HR_PASSWORD
        sync: false
      - key: HR_URL
        value: https://hr-erp.shivnadarfoundation.org/Adrenalin/
      - key: GOOGLE_CHAT_WEBHOOK
        sync: false
      - key: DISCORD_WEBHOOK
        sync: false
